services:
  app:
    build:
      context: .
      args:
        SERVER_PORT: ${APP_PORT_CONTAINER}
    image: ${APP_IMAGE_NAME}
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${APP_PORT_HOST}:${APP_PORT_CONTAINER}"
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ${FIREBASE_CONFIG_PATH}:/app/resources/firebase-key.json
    networks:
      - sugang-helper-network-server


# Networks and Volumes are managed in the root docker-compose.yml


